Lo 5 add jpa repositories
lopez-org/bank pull request #6
Opened 2023-12-12 21:27 UTC by JuanLopezMELI

## Summary
Se agregan los repositorios de JPA

## Why is this necessary?
Se requiere consultar la información en la base de datos para cada entidad

## JIRA issue link
[LO-5](https://lopez-org-bank.atlassian.net/browse/LO-5)

## How had we tested it?
No se ha testeado aún

## What have we done?

- [ ] Bug fix (un cambio que no rompe código existente y corrige un problema)
- [X] New feature (Un cambio que no rompe código existente y agrega funcionalidad)
- [ ] Breaking change (Un cambio que rompe la compatibilidad con versiones anteriores y arregla un problema o agrega funcionalidad)

## Checklist:

- [X] Mi código sigue el estilo de este proyecto.
- [X] Mi cambio requiere actualizar en documentación.
- [X] Actualicé la documentación.
- [ ] Agregué tests para cubrir mis cambios.

2023-12-12 23:45 UTC, DahierQuintero commented
Muy bien, veo que solo hace falta la anotación @Repository en "AppUserRepository" y "PocketRepository" para que Spring los reconozca. Creo que a "Person" no es necesario crearle Repositorio, se puede omitir esa interfaz.

2023-12-13 14:25 UTC, JuanLopezMELI commented
> Muy bien, veo que solo hace falta la anotación @repository en "AppUserRepository" y "PocketRepository" para que Spring los reconozca. Creo que a "Person" no es necesario crearle Repositorio, se puede omitir esa interfaz.

Se agregan las anotaciones, pero se decide dejar el PersonRepository. AppUser contiene contraseñas. Puede que haya momentos en los que queramos traer datos del usuario sin necesidad de tener que manejar su contraseña. Para estos casos, la entidad Person sería muy útil. Además de que nos permitiría tener info de posibles clientes, sin necesidad de que ya sean usuarios de la aplicación.

2023-12-13 20:41 UTC, DahierQuintero requested changes
Lo veo bien, solo falta confirmar el detalle que te puse, el resto es aprobado

2023-12-13 20:41 UTC, DahierQuintero commented on src/main/java/com/mjd/bank/entities/Account.java
Juan Pa, no sé si sea necesario el atributo "id" auto incrementable en "Account". Creo que es mejor quitarlo y que el @Id sea en "number", ya que no pueden existir 2 cuentas con el mismo número.

2023-12-13 21:53 UTC, JuanLopezMELI commented on src/main/java/com/mjd/bank/entities/Account.java
Hecho

2023-12-13 22:04 UTC, DahierQuintero approved these changes
Excelente trabajo.

2023-12-14 03:39 UTC, merged